# Generated by Django 5.2 on 2025-05-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("code", "Bộ luật"),
                            ("law", "Luật"),
                            ("decree", "Nghị định"),
                            ("resolution", "Nghị quyết"),
                        ],
                        max_length=50,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("tag", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("source_url", models.URLField()),
                ("crawl_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
